SPbAU. Software Design course.
svloyso/sdcourse.shell pull request #1
Opened 2016-09-22 21:59 UTC by svloyso

@yurii-litvinov

2016-09-26 05:00 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/Ls.java
> +public class Ls extends Command {
а зачем Вы реализовывали ls? это часть следующей домашки, чтобы ls реализовал кто-то другой :)

2016-09-26 05:00 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/OutputWritter.java
> +public class OutputWritter extends Command {
Writer

2016-09-26 05:01 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/Wc.java
> +        int words = 0, lines = 0, chars = 0, longest = 0;
объявления лучше каждое на отдельной строчке

2016-09-26 05:01 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/ExitException.java
> +public class ExitException extends Exception {
тоже неплохо бы содержательный комментарий

2016-09-26 05:05 UTC, yurii-litvinov requested changes
- под виндой сразу же упало на строке 28 CommandFactory.java с исключением
  java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Students/SoftwareDesign-Solutions/604/svloyso/target/classes/\ru/spbau/sdcourse/Commands
- ещё нужна диаграмма с архитектурой и короткое архитектурное описание словами
- ещё много замечаний по стайлгайду, которые я все не стал отмечать, откомментив только один-два типичных случая. я понимаю, что стайлгайд у всех разный, но есть (особенно в мире Java) сложившиеся традиции и практики, которых лучше не нарушать. поправьте, пожалуйста.

2016-09-26 05:05 UTC, yurii-litvinov commented on pom.xml
> +    <description>Simple shell</description>
табуляции и пробелы перемешаны, поэтому всё так некрасиво

2016-09-26 05:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/Args.java
> +        if (arguments.size() < 1) throw new Exception("args: no command was given");
с точки зрения стайлгайда лучше

``` java
if (arguments.size() < 1) {
    throw new Exception("args: no command was given");
}
```

2016-09-26 05:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/Args.java
> +        while((line = getLine()) != null) {
опять-таки с точки зрения стайлгайда между ключевыми словами и скобкой обычно ставится пробел:

``` java
while ((line = getLine()) != null) {
```

2016-09-26 05:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/CommandFactory.java
> +     * @param env enviroment
environment

2016-09-26 05:05 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/CommandFactory.java
> +        if(builtinCommands.containsKey(name)) {
здесь тоже, пробела не хватает

2016-10-18 18:02 UTC, svloyso commented
@yurii-litvinov 
Исправил ваши замечания.

2016-11-22 23:11 UTC, yurii-litvinov requested changes
На диаграмме наследование рисуется не в ту сторону, треугольники должны быть у предка. И не пунктирной линией, а сплошной --- Command класс и от него именно наследование, а не реализация интерфейса.

Ещё нужно короткое архитектурное описание словами, либо рядом с диаграммой, либо отдельным документом.

2016-11-22 23:11 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Shell.java
> +        boolean inStrong = false, inWeak = false;
Лучше каждое объявление на своей строке

2016-11-22 23:11 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Shell.java
> +            if(text.charAt(pos) == '"' && !inStrong) inWeak = !inWeak;
Идеологически более правильно с точки зрения стайлгайда так:
```java
if (text.charAt(pos) == '"' && !inStrong) {
    inWeak = !inWeak;
}
```

2016-11-22 23:11 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Shell.java
> +            if(text.charAt(pos) == '\'' && !inWeak)  inStrong = !inStrong;
Вообще, кстати, в джаве вроде как принято разделять пробелом ключевое слово и открывающую скобку, а лучше придерживаться общепринятых соглашений, если нет веских причин поступать иначе.

2016-11-22 23:11 UTC, yurii-litvinov commented on src/test/java/ru/spbau/sdcourse/ShellTest.java
> +                Paths.get(resDir, execFile).toAbsolutePath().toString(),
Так оно под виндой тоже не работает. Впрочем, это можно не править.

2016-11-22 23:11 UTC, yurii-litvinov commented on src/main/java/ru/spbau/sdcourse/Commands/Grep.java
> +                    throw new Exception("grep: invalid key " + arg);
В задаче просили воспользоваться одной из библиотек разбора командной строки. Иначе оно, например, не умеет принимать файл из командной строки, надо cat делать:
&gt; grep plugin pom.xml
grep: invalid key plugin

2020-12-18 12:59 UTC, merged